### PR TITLE
fix(frontend): Dates in SSR are not rendered in user language

### LINKED ISSUE #871: The datetime not rendered in user's language
With the recent i18n code refactor, it seems now in pages like Account and Transaction, etc., the default language for date is Russian when rendering the page returned by SSR.

To reproduce, try open the page in browser: https://explorer.near.org/accounts/alice.near   

image

The date is in Russian, even if I switch the language to Chinese.

image

To fix this, in SSR, we should render the date in the selected language.

### PR DESCRIPTION
**Pull request by luixo**
Resolves #871

### CODE REVIEW

**Comment by frol** [comment]
@luixo I still don't see the issue fixed in the preview: https://near-explorer-experimental-frontend-with-0ej6.onrender.com/blocks/2N25LVv5DcwuH1yMtycpwgpAk3aS72rNKXwcuYjiNBdd

**Comment by luixo** [comment]
How can I reproduce the bug?
I tried the following:
1. Open the page
2. Set language to russian
3. Change language in cookie to 'en'
4. Reload page with js toggled off
5. Verify that date is in english

The only problem I encountered is that after page load I have a blink changing language to russian (probably, based on my browser language) and then back to english.
I will try to fix this now with instant moment locale set.

**Comment by shelegdmitriy** [comment]
> How can I reproduce the bug? I tried the following:
> 
> 1. Open the page
> 2. Set language to russian
> 3. Change language in cookie to 'en'
> 4. Reload page with js toggled off
> 5. Verify that date is in english
> 
> The only problem I encountered is that after page load I have a blink changing language to russian (probably, based on my browser language) and then back to english. I will try to fix this now with instant moment locale set.

@luixo try to open this page in a private window. I was only able to reproduce it this way. But still, when I open any page in a private window, the date will be displayed in Russian, but after a few seconds it will change to the selected language.

https://user-images.githubusercontent.com/34593263/151141924-85ab470b-c6ea-429f-bf9a-2079ee4ec2dd.mov

**Comment by luixo** [comment]
> try to open this page in a private window. I was only able to reproduce it this way. But still, when I open any page in a private window, the date will be displayed in Russian, but after a few seconds it will change to the selected language.

Yeah, the bug exists in production, but I fixed it in this PR, and @frol says it is still here. Can you reproduce it on the render stage?

**Comment by shelegdmitriy** [comment]
> How can I reproduce the bug?

I misunderstood you, sorry.

> Can you reproduce it on the render stage?

I can't reproduce it anymore

**Comment by luixo** [comment]
I wait for an approve then!

**Review by shelegdmitriy — APPROVED** [review]
LGTM. Let's wait for @frol review. Maybe he knows some cheat-code to break this fix 😀

**Comment by luixo** [comment]
Sorry, it was auto-merged. I hope he'll tell us if he knows how to repro this.

**Pull request merged**
