### PR TITLE
Always use React.memo

### PR DESCRIPTION
**Pull request by luixo**
This PR should raise a discussion about using namespaces.
Should it be
```
import * as React from 'react';
const MyComp: React.FC = () => {...};
```
or
```
import {FC} from 'react';
const MyComp: FC = () => {...};
```
?

The chosen option should be enforced by linter.
@shelegdmitriy any ideas?

### CODE REVIEW

**Comment by luixo** [comment]
Also, an article on topic that explains why we should not skip `memo`: https://attardi.org/why-we-memo-all-the-things/

**Review by frol — APPROVED** [review]
I am fine with using `memo` everywhere, but the way we currently apply it over the whole function body makes it hard to read the props list, and sometimes adds another indentation level. In case of custom equality rules passed to `memo` as a second argument, it will make things even worse. Would you consider applying `memo` at the bottom of the file on export?

**Comment by frol** [comment]
> This PR should raise a discussion about using namespaces.

I usually prefer explicit namespacing (`React.FC`) to ease reading, but with tree-shaking JS seems to need to import selectively (unless some heuristics were already implemented and I have outdated information).

**Comment by luixo** [comment]
> Would you consider applying memo at the bottom of the file on export?

I have no problem with that except the fact we'll probably want a eslint rule for memo and tracking `memo`s on export is harder than tracking them inline.

> I usually prefer explicit namespacing (React.FC) to ease reading, but with tree-shaking JS seems to need to import selectively (unless some heuristics were already implemented and I have outdated information).

Yep, it's outdated, even nested import tree-shaking is [supported](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#nested-tree-shaking) in Webpack nowadays.

**Review by shelegdmitriy — APPROVED** [review]
I'm fine with this option totally:
```
import * as React from 'react';
const MyComp: React.FC = () => {...};
```

**Pull request merged**
