### PR TITLE
fix(frontend): Transaction list is always loading when search at second time

### PR DESCRIPTION
**Pull request by IsQiao**
Screen Recording 2021-04-22 at 10 33 15 AM

### CODE REVIEW

**Comment by think-in-universe** [comment]
thanks @IsQiao!

Step to reproduce:

1. go to page https://explorer.testnet.near.org/accounts/robertyan.testnet, the transactions are loaded successfully
2. in the same page, search **bot.testnet** in the search box, the account info  are turned but transaction history is always loading

**Comment by frol** [comment]
@shelegdmitriy Please, review if that patches the issue #541.

**Comment by frol** [comment]
@IsQiao Thanks for your contribution! I will review this PR tomorrow.

**Comment by shelegdmitriy** [comment]
@frol, yeah it resolves not only #541 but even #492.

@IsQiao well done!

**Review by shelegdmitriy — APPROVED** [review]

**Review by frol — APPROVED** [review]
@IsQiao Looks good to me! Thanks for the fix!

May I ask how complex was getting the project running on your end to contribute? Let's say on a scale from 1 (completely lost) to 5 (as easy as it could be)

**Comment by IsQiao** [comment]
> @IsQiao Looks good to me! Thanks for the fix!
> 
> May I ask how complex was getting the project running on your end to contribute? Let's say on a scale from 1 (completely lost) to 5 (as easy as it could be)

Almost 4, i just run the frontend project. But i try run total solution on container(include backend), it's very slow.

**Pull request merged**
