### PR TITLE
feat: New Display information and statistic on dashboard without chart

### PR DESCRIPTION
**Pull request by icerove**
partially addressed #350 
2. fix the node and block card
3. fix the transaction card without chart

### CODE REVIEW

**Comment by frol** [comment]
@icerove given the plan @corwinharrell [suggests](https://github.com/near/near-explorer/discussions/470#discussioncomment-125801):

>  We shouldn't ship any changes from the dashboard refresh until we feel like confident that the design changes applied site-wide are consistent, and that it doesn't feel like the dashboard is too divergent from the other views.

I suggest we land all the changes to the backend in a separate PR, so we can land it first, so we have the Render PR URL working fine. Could you do that?

**Comment by frol** [comment]
On the other hand, in that case we will be required to make sure we don't break the currently deployed frontend (the stats should be additive instead of replacing one with another)

**Comment by icerove** [comment]
remember to pull the latest change I made. @frol

**Comment by frol** [comment]
@icerove I have deployed the backend and frontend to new instances on Render, so we can test it online with @corwinharrell and anyone willing to give it a try., but it currently fails due to TypeScript errors. Please, fix those and you should be able to see the deployed version on https://near-explorer-frontend-redesign.onrender.com/

**Comment by frol** [comment]
The tests fail due to:

```
ERROR in /near-explorer/frontend/src/components/dashboard/DashboardHeader.tsx(88,33):
Property 'totalTransactions' does not exist on type '{ finalTimestamp: number; latestBlockHeight: number; latestGasPrice: string; numberOfLastMinuteBlocks: number; transactionCountArray: never[]; lastDayTxCount: number; last2DayTxCount: number; }'.
```

Please, address that

**Pull request closed without merging**
