### PR TITLE
feat(frontend): NEAR Explorer translation for Vietnamese Users

### PR DESCRIPTION
**Pull request by that83**
Contribution to the bounty: https://github.com/near/bounties/issues/62

### CODE REVIEW

**Comment by frol** [comment]
@that83 Thank you for the contribution!

@shelegdmitriy Please, review the changes

**Comment by that83** [comment]
[Screenshot Test NEAR Explorer #62.xlsx](https://github.com/near/near-explorer/files/6958506/Screenshot.Test.NEAR.Explorer.62.xlsx)
I am sending the screenshot file for reference. Thank you.

**Comment by think-in-universe** [comment]
@that83 thanks for the contribution! LGTM.

btw, could you please ask another 1~2 Vietnamese developers to help review the translation?

**Comment by shelegdmitriy** [comment]
@that83 thanks for the contribution, LGTM. There is a missed part, but it was missed earlier, so I don't know does it must be resolved in this particular PR by you or not. @Frol Vlad what do you think about it? 
Снимок экрана 2021-08-10 в 15 38 46

**Review by shelegdmitriy — APPROVED** [review]

**Comment by frol** [comment]
@shelegdmitriy That part have to be addressed separately once we implement i18n for that component, so it should not be part of this PR

**Comment by think-in-universe** [comment]
@shelegdmitriy nice catch. 

@IsQiao will help add the missing i18n support in the **ValidatorRow** component. 😃  thanks!

**Comment by ducviet00** [comment]
Hi, Vietnamese developer here! I will review all translations in this work 😃

**Comment by ducviet00** [comment]
> @that83 thanks for the contribution! LGTM.
> 
> btw, could you please ask another 1~2 Vietnamese developers to help review the translation?

Vietnamese developers here! 
It's good but some translations can be made more clearly.
Like this one !
image

**Comment by that83** [comment]
@ducviet00 Thank you! Would you mind giving your suggest words?

**Comment by that83** [comment]
I have just updated several Vietnamese words base on reviewer's comments ( ducviet00 and BaoAnh).
Thank you.

**Comment by frol** [comment]
@that83 @ducviet00 @think-in-universe Yay! It is live! Please, review it on production once again :pray:

**Comment by think-in-universe** [comment]
wow, great work @that83 @ducviet00 !! 🚀 

thanks @frol! this is awesome!

**Comment by that83** [comment]
Thank you. I have reviewed, LGTM.
BTW, why data of some charts are not shown?
image

**Comment by ducviet00** [comment]
> @that83 @ducviet00 @think-in-universe Yay! It is live! Please, review it on production once again 🙏

I've reviewed it, seems good!


> Thank you. I have reviewed, LGTM.
> BTW, why data of some charts are not shown?
> image

it doesn't belong to this feature. [near/near-indexer-for-explorer#137](https://github.com/near/near-indexer-for-explorer/issues/137)

**Pull request merged**
