### PR TITLE
refactor: Upgrade Next.js

### PR DESCRIPTION
**Pull request by luixo**

### CODE REVIEW

**Review by frol — APPROVED** [review]
This was suspiciously straightforward. Are there any new deprecation warnings?

**Comment by frol** [comment]
I checked the warnings myself. It seems that we may want to see if we can drop `.babelrc`:

image

@luixo just a friendly ping, there is a merge conflict here.

**Comment by luixo** [comment]
> Are there any new deprecation warnings?

Didn't check for them. Thanks for pointing out!

> It seems that we may want to see if we can drop .babelrc:

Yep, that's the way to SWC (Rust-based compiler), I'll try to eliminate babel.

**Comment by luixo** [comment]
@frol I removed `.babelrc` to enable SWC in Next.js, but put it back in Jest until the next PR resolve it.
Ready for review!

**Review by frol — APPROVED** [review]
LGTM!

**Review by shelegdmitriy — APPROVED** [review]

**Pull request merged**
