### PR TITLE
Feature: nodemon on backend

### PR DESCRIPTION
**Pull request by luixo**

### CODE REVIEW

**Comment by frol** [comment]
@luixo what problem does it solve? (I am just curious)

**Comment by luixo** [comment]
It restarts backend automatically on source code changes while developing.

**Comment by shelegdmitriy** [comment]
> It restarts backend automatically on source code changes while developing.

So you don't need to restart backend manually after each change of backend file?

**Comment by luixo** [comment]
Exactly

**Review by shelegdmitriy — APPROVED** [review]

**Pull request merged**
