### PR TITLE
DRAFT: feat: Migrate to pagoda rpc

### PR DESCRIPTION
**Pull request by shelegdmitriy**
Closes https://nearinc.atlassian.net/browse/DEC-528

### CODE REVIEW

**Review by luixo — COMMENTED** [review]
Should we also migrate production values (`render.yml`)? Please upload keys to `render.com` "secret" env variables storages before merging this.

Did you run it locally?

**Comment by shelegdmitriy** [comment]
> Please upload keys to `render.com` "secret" env variables storages before merging this.

Oh, I missed that. Will do

**Comment by shelegdmitriy** [comment]
> Did you run it locally?

Yes. I tried both: mainnet and testnet and everything was OK.

**Review by luixo — APPROVED** [review]
> Oh, I missed that. Will do

Don't forget to do that on production secret storages as well before merge.

**Comment by frol** [comment]
BTW, it seems that e2e tests need RPC credentials

**Comment by shelegdmitriy** [comment]
> BTW, it seems that e2e tests need RPC credentials

That's right. I'm working on it

**Comment by luixo** [comment]
Let's reopen that when Pagoda RPC will be able to provide archival data.

**Pull request closed without merging**
