### PR TITLE
Fix: Infinite loop on BN.js null instead of 0

### PR DESCRIPTION
**Pull request by luixo**
Resolving bug introduced by `bn.js`: https://github.com/indutny/bn.js/issues/186

### CODE REVIEW

**Comment by shelegdmitriy** [comment]
> I believe something's broken on Render integration side as I changed its settings extensively. I'll look into this.

Ok, I'll check this locally, not a big deal

**Comment by shelegdmitriy** [comment]
> 49MysHDCtYNQsLXbuDksbFgYthKZHN6GANRgqJqqzAdN

Yeah, that's exactly what I vanted to check because we had some issue (which I can't find) with this. But it works fine now

**Review by shelegdmitriy — APPROVED** [review]

**Review by frol — APPROVED** [review]
I am ok with this as a quick fix, but let's have a TODO properly handling the error since with this behavior we risk to misinform users about the actual gas usage

**Comment by luixo** [comment]
Before we had this changed the page blew with 500, I believe we have an improvement :)

**Comment by luixo** [comment]
> Yeah, that's exactly what I wanted to check because we had some issue (which I can't find) with this. But it works fine now

It's testnet by the way

**Pull request merged**
